### ISSUE TITLE
connecting with AUTH TLS hangs

### ISSUE THREAD

**Issue by davekimble2** [mimecuvalo/fireftp#122]
Client: Ubuntu 14.04, Firefox 36.0.1, Fireftp 2.0.22
Server: Linux shared hosting, possibly my SSL certificate not installed properly

When trying to connect with FireFTP > Edit >  Connection > Security: Auth TLS (best) 
a window appears saying the certificate info doesn't match the domain (I think it is the certificate of the host of my shared hosting) and do I want to make an exception? 
Click "Make an exception" shows another dialog. 
"Get Certificate" shows Checking Info and then hangs with all buttons disabled except Cancel, which doesn't work.

![ftp screenshot](https://cloud.githubusercontent.com/assets/6146050/6703627/2c49eeda-cd8a-11e4-99cb-5bf0499ed0c3.png)

I can't resolve my certificate problem yet, and want to make an exception for  the hosts certificate for now.

**Comment by Meserias** [comment]
I have a similar issue ..... 
This window appear first:
![1a](https://cloud.githubusercontent.com/assets/12730634/7959436/c7567732-0a01-11e5-93a6-2f8f65cc4f39.png)
then I'm stuck on window that davekimble2 posted already.

**Comment by mimecuvalo** [comment]
related to #103 which, in turn, is related to https://bugzilla.mozilla.org/show_bug.cgi?id=478322
