### ISSUE TITLE
File type icons not displaying

### ISSUE THREAD

**Issue by Anorionil** [mimecuvalo/fireftp#133]
It has been been noted numerous times in the reviews of the addon: the file type icons are not displaying properly.

"since approx. the time i updated to ff 36, the file type icons are not displayed in either the local or remote view until the files in the lists are moused-over
win 7
ff 36.0.1
fftp 2.0.22"
![fireftp_bug](https://cloud.githubusercontent.com/assets/12167281/7387545/2e4a78ea-ee5e-11e4-9174-eeda74855163.png)

**Comment by mimecuvalo** [comment]
dupe #130
