### ISSUE TITLE
deleted directory still showing in fireFTP

### ISSUE THREAD

**Issue by PalmerAL** [mimecuvalo/fireftp#135]
I've been using fireFTP for months and never had an issue with it, but suddenly it isn't working correctly.

I was trying to delete a folder on the server that had several folders inside of it, Of the folder I was trying to delete, fireFTP deleted all the subfolders, but then could not delete one of the subfolders. It gave the message "550 Can't remove directory: Directory not empty", even though there was clearly nothing in the folder. I then went to the hosting provider's website (goDaddy), and used their file manager to delete the folder I was trying to delete. At this point, the folder is clearly gone - it doesn't show in goDaddy's file manager anymore, and attempting to go to the folder on the server results in a 404. However, fireFTP still shows the deleted folder and the subfolder it failed to delete in the file tree. Whenever I try to actually access the deleted folder it shows as still existing, it gives a 503 error. Is there anything I can to do to get it to remove this nonexistent folder?

**Comment by mimecuvalo** [comment]
Hm, that's strange.  Perhaps it's because there's a hidden file or folder in there.  Go to your FireFTP settings (tools->options) and turn on hidden files.

**Comment by PalmerAL** [comment]
Oddly, the folder isn't showing any more. Thanks for the suggestion, though!
