### ISSUE TITLE
I am only seeing a blank page after connection.

### ISSUE THREAD

**Issue by Brian1111** [mimecuvalo/fireftp#136]
I have been using FireFTP for more than two weeks with no problem.  Today suddenly the screen became blank, and I am not seeing the folders and files anymore even though I am connected.  I deleted my account and created the same account again, still after connection I am seeing only a blank page instead of folders and files.

**Comment by mimecuvalo** [comment]
What is the error that you see on your screen?  Is there anything in the log showing up?
