### ISSUE TITLE
Unusual password request

### ISSUE THREAD

**Issue by thomschreck** [mimecuvalo/fireftp#137]
When I launch FireFTP, it requests my salesforce and lending club passwords stored in KeePass. KeePass has replaced the firefox password manager using the extension PassIFox. 

This is a new firefox installation, and I can replicate the condition by launching FireFTP. 

![2015-06-05_16h12_53](https://cloud.githubusercontent.com/assets/3483975/8014439/c6ef1e22-0b9e-11e5-9851-25a3ac79b2e2.png)

**Comment by mimecuvalo** [comment]
FireFTP does save passwords through the Firefox password manager of your FTP accounts.  That's probably why it's asking for them.
