### ISSUE TITLE
hotkeys

### ISSUE THREAD

**Issue by ildarkhasanshin** [mimecuvalo/fireftp#141]
1. I can not find a full list of keyboard shortcuts to help.
2. Do you plan to add a dialog to add a custom hot keys?

**Comment by mimecuvalo** [comment]
There isn't a plan to add more custom hot keys.  The keyboard shortcuts are only ones that are typical for a local operating system file browser.

**Comment by ildarkhasanshin** [comment]
has list of standart hotkeys?
1 switch left/right panel?
2 goto address-field?

**Comment by ildarkhasanshin** [comment]
up

**Comment by mimecuvalo** [comment]
Patches / ideas welcome for these feature additions!
