### ISSUE TITLE
FTPS connections to box.com failing

### ISSUE THREAD

**Issue by rardin** [mimecuvalo/fireftp#143]
I've been using FireFTP to connect to box.com's FTP server, ftp.box.com, utilizing FTPS protocol [Security: Auth TLS (Best)], but ran into issues after updating to Firefox 31.8.0esr.  I did some testing this morning with FireFTP versions 2.0.19 and 2.0.24 and several versions of Firefox for Mac OS X:

FireFTP 2.0.19:
works with Firefox 31.7.0esr
fails with Firefox 31.8.0esr
fails with Firefox 38.1.0esr
works with Firefox 38.0
works with Firefox 38.0.1
works with Firefox 38.0.5
fails with Firefox 39.0

FireFTP 2.0.24:
fails with Firefox 38.1.0esr
works with Firefox 38.0
works with Firefox 38.0.1
works with Firefox 38.0.5
fails with Firefox 39.0

Messages like the following are logged by FireFTP for connections that work:
220 Service ready for new user.
AUTH TLS
234 Command AUTH okay; starting TLS connection.
PBSZ 0
200 Command PBSZ okay.
USER 
331 User name okay, need password for .
PASS (password not shown)
230 User logged in, proceed.
FEAT
etc.

The following messages are logged for connections that don't work:
220 Service ready for new user.
AUTH TLS
234 Command AUTH okay; starting TLS connection.
PBSZ 0

The behavior is the same whether I make a quick connection (and enter the password on the fly) or use a connection that I've saved and for which the password has been stored by Firefox.

**Comment by rardin** [comment]
Problem was related to the Logjam vulnerability:
https://support.mozilla.org/en-US/questions/1065417

The workaround was to disable a couple old ciphers in Firefox, which presumably forces box.com to try another, more secure cipher when an FTPS connection is opened by FireFTP:

about:config
Search: security.ssl3.dhe
toggle these to false:
security.ssl3.dhe_rsa_aes_128_sha
security.ssl3.dhe_rsa_aes_256_sha

**Comment by mimecuvalo** [comment]
Sorry for the delay in response - I've been extraordinarily busy at work.

Glad you were able to find a solution.

**Comment by mimecuvalo** [comment]
I'll post this to another bug - hopefully it will be useful to others!
