### ISSUE TITLE
Transfer Overwrite Always

### ISSUE THREAD

**Issue by IT-Serenity** [mimecuvalo/fireftp#150]
I am tired of being asked if I want to Overwrite / Overwrite all / etc...

I want it to remember that I want it to Overwrite in both directions ALWAYS....  each and every time!

**Comment by mimecuvalo** [comment]
You can do this in Tools->Options->Downloads/Uploads->Don't display overwrite dialog, simple overwrite.

**Comment by mimecuvalo** [comment]
You can do this in Tools->Options->Downloads/Uploads->Don't display overwrite dialog, simple overwrite.
