### ISSUE TITLE
Google Authenticator support

### ISSUE THREAD

**Issue by francoism90** [mimecuvalo/fireftp#153]
When using Google Authenticator as extra authentication protection for a Linux-server, I'm unable to login when using FireFTP (keeps saying authentication failed).

`sshfs` supports this authentication-method. Is it possible to add this to FireFTP? :)
See https://wiki.archlinux.org/index.php/Google_Authenticator and https://github.com/google/google-authenticator for details.

Thanks!

**Comment by mimecuvalo** [comment]
Would be good to add!  I'm very busy this year so in the meantime, patches are heartily welcome ^_^
