### ISSUE TITLE
Stopped working with FF 44.0  UG on WIN 10 Pro x64

### ISSUE THREAD

**Issue by thomastownsend** [mimecuvalo/fireftp#162]
I just UG FF to latest release 44.0 and now Fire FTP Crashes FF every time (repeatable) 

I have uninstalled and re-installed - same. 

> Totally useless.

O/S Windows 10  Pro Version 1511 OS Build 10586.7

**Comment by mimecuvalo** [comment]
Hm, I'm not sure why it would be doing that :-/  In these cases, I recommend doing:
https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings

**Comment by thomastownsend** [comment]
Fire FTP has become "obsolete" and "TOTALLY USELESS" since it has not been updated to work/support - PORT 2222 for SFT on many hosts.  I really used to like this plugin feature but lack of a fix for this has caused me to move onto FILE ZILLA.   RIP....

**Comment by mimecuvalo** [comment]
Please keep conversation civil and polite.  Sorry it did not work out for you.
