### ISSUE TITLE
XSHA1 check fails on large files

### ISSUE THREAD

**Issue by mrobe** [mimecuvalo/fireftp#163]
Using OS X 10.10.5, I am unable to download files without the following error: "The transfer of this file was unsuccessful and resulted in a corrupted file. It is recommended to restart this transfer." It seems to happen each time I download a large file (i.e., more than 2 GBs).

This is with FireFTP 2.0.26 "Nature Boy"

It seems that the XSHA1 check fails each time. I can provide more details, as necessary.

**Comment by mimecuvalo** [comment]
Thanks for the info - does the file actually transfer correctly?  Is it only the XSHA1 check that fails?

**Comment by mrobe** [comment]
I have been having problems with file corruption, so really I don't know.

Is there some way to verify that the file transferred correctly using the OS X command line?

**Comment by mrobe** [comment]
To clarify, looking at the log here's my best guess at what is happening...

I try to download a big file using FireFTP. The data transfer finishes, but some kind of timeout occurs, so the client sits for while, gives up, and then resumes the transfer using REST. About this timeout, I see it almost every time I transfer a large file. It seems the "226 Transfer complete" message is never received, so the client eventually gives up, sends QUIT, reopens the connection, and then tries REST + RETR.

Next, it seems the whole file was in fact already transferred, so the client asks to resume from the last byte in the file. E.g., if the file was reported as 7811842048 bytes long when the RETR command was sent, the attempt to restart is REST 7811842048. I don't know what the effect of trying to restart from the end of the file is, but maybe(?) the client is doing something wrong here.

Next, the client quickly finishes the REST + RETR transfer, receives the expected "226 Transfer complete", and then performs the XSHA1 check, which fails.

I found that OS X includes an implementation of SHA1 as part of openssl, so I generated the hash of the local file like this:

       % /usr/bin/openssl sha1 myFile

The hash does not match the result of the XSHA1 command sent to the server, which is consistent with the error reported by FireFTP.

So here I am stuck. Is the file corrupted? I don't know.

I have a few thoughts about this...

(1) Why does the initial transfer fail due to a timeout? I changed the FireFTP settings so that **Connection Recovery > Network timeout** is 200 seconds, and that **Keep connective alive when idle** is enabled. Still, I am seeing a timeout on RETR. Here, I am going to speculate a bit, based on past experience. IIRC, FTP actually has two network streams. One is for exchanging command messages with the server, and the other for transferring data. If the control connection is lost during RETR, the data connection may continue to the end, but the 226 message from the server never arrives. The control connection may be lost due to, for example, a router terminating it. I don't remember the details of this, or how I should debug it, but any suggestions you might have would be appreciated.

(2) It might be that REST from the end of the file is causing corruption, then causing the SHA1 hash to be incorrect. I checked the length of the local file after FireFTP was finished, and it is the same number of bytes as reported by the server when RETR was started, so FireFTP isn't messing up the length of the file, but maybe something is going wrong such that the last block of the file is getting corrupted.

(3) It is possible (though it seems unlikely) that the server implementation of XSHA1 has a bug, so it is reporting the hash incorrectly. The server implementation is ProFTPD 1.3.5. I did a Google search of "ProFTPD" "XSHA1" to see if anything comes up, but I don't find any obvious reports of bugs in their implementation. It is of course also possible that the OS X implementation is not the same, so the hashes are different for the same file. Again, this seems unlikely.

That's all I can think of right now.

My feeling is that most likely there is a bug in FireFTP, because REST+RETR should work. I would also like to figure out the problem with the transfer being lost due to a timeout, though that is (I think) a separate issue.

What should I try next?

**Comment by mrobe** [comment]
Following up with another observation: I tried downloading the same file with FileZilla and then generating an SHA1 hash on my workstation. It is the same as the hash for the file downloaded with FireFTP. FileZilla had a problem with a dropped connection too, but it restarted and the hash checks out. I then noticed that I didn't have passive mode enabled on FireFTP, so I tried that and downloaded the file yet again. This time, I got "226 Transfer complete" as expected, and the transfer completed normally. The hash checks out.

Then, I noticed that the server's answer to the XSHA1 command is not the same hash value as it was when I tried this a few hours earlier. Maybe I am misunderstanding something here, but I thought these hash values are supposed to be the same for the same file, regardless of the platform or machine?

If that's true, then could it be the problem is actually a bug in the FTP server??

**Comment by mrobe** [comment]
I tried **Tools** > **Custom Command...** to send XSHA1 to the server. If I send the same command three times, I get three different hashes.

So, in fact this appears to be a problem with the server. I'm talking with the ProFTPD developers, so I'll close this issue.

**Comment by mimecuvalo** [comment]
Thanks for such a thorough explanation and for digging into the issue!  That last idea was great debugging.
Let me know if there's a bug filed on ProFTPD somewhere - I'd be curious to follow along.

**Comment by mrobe** [comment]
Yes, the ProFTPD developers suggested there might be an issue with the mod_digest component, and that I should upgrade to the latest RC. However, I'm not the sysadmin for the server, so I must wait for him to update to the next point release. Once that's done, I'll try it again. Meanwhile, thanks again for FireFTP!
