### ISSUE TITLE
Cannot add SSL exception when IP is used instead of domain

### ISSUE THREAD

**Issue by TheEvilDoctor** [mimecuvalo/fireftp#172]
On the server we have FileZilla running with a self-signed SSL certificate.  As our FTP does not relate to domains (but instead is a backup solution), our host in FireFTP is an IP address and not a domain name.

When connecting via TLS for the first time, the "invalid security certificate" error appears as expected.
When choosing to add an exception, the Get Certificate button does not work.  Instead an error appears, "Unable to obtain identification status for this site".  
The Location field in the exception dialog shows the IP address followed by :21

It used to work fine (and did for a long time), but no longer does.

**Comment by mimecuvalo** [comment]
Hrm, I don't have much control over that dialog - it's on the Firefox side of things - you can try filing a bug with Mozilla: https://bugzilla.mozilla.org/

Lemme know how it goes - it could be a regression in Mozilla possibly?

**Comment by TheEvilDoctor** [comment]
No problem - thanks for clarifying - and keep up the excellent work on that awesome extension!
https://bugzilla.mozilla.org/show_bug.cgi?id=1263561

**Comment by mimecuvalo** [comment]
Thanks to mozkeeler for the patch and for TheEvilDoctor for raising it to Mozilla!

**Comment by mimecuvalo** [comment]
I'll probably push out a new version of FireFTP next week.
