### ISSUE TITLE
SFTP cannot connect

### ISSUE THREAD

**Issue by Wendihihi** [mimecuvalo/fireftp#176]
I'm not able to connect with SFTP from today. FireFTP 2.0.27. Waterfox 47.0. FF 47.0. Updated Waterfox and FF today.

**Comment by mimecuvalo** [comment]
Bug is being tracked here: https://github.com/mimecuvalo/paramikojs/issues/9
Thanks for the feedback!  Moving work there.

**Comment by mimecuvalo** [comment]
Fixed now - sorry for the inconvenience! :-/
