### ISSUE TITLE
Chrome FireFTP?

### ISSUE THREAD

**Issue by deadfreak** [mimecuvalo/fireftp#179]
http://i.imgur.com/5EIaYTq.png

Stop playing games with our heart developer! No, but seriously is it planned?

**Comment by mimecuvalo** [comment]
Oops, that's a typo :)  It's cross-platform for FireSSH but not for FireFTP.  Besides Chrome Web Store is shutting down... :-/ 

http://blog.chromium.org/2016/08/from-chrome-apps-to-web.html
