### ISSUE TITLE
Disconnect after 500 'FEAT': command unrecognized

### ISSUE THREAD

**Issue by jimbabwe7** [mimecuvalo/fireftp#182]
Hi and thank you for FireFTP!

I have been using FireFTP for some years, just fine, on Windows XP SP2.

A monthly task is to log into my 1&1 hosting account and delete 40,000 .jpg files from a directory.

 FireFTP 2.0.28 'Nature Boy' designed by Mime Čuvalo in Croatia

SSH component is ported from Paramiko 1.7.7.1, created by Robey Pointer

220 FTP Server ready.
       USER u60615865
331 Password required for u60615865
       PASS (password not shown)
230 User u60615865 logged in
       FEAT
500 'FEAT': command unrecognized.

```
   PWD
```

257 "/" is the current directory
       TYPE A
200 Type set to A
       PASV
227 Entering Passive Mode (74,208,215,227,233,137).
       LIST -al
150 Opening ASCII mode data connection for file list
226 Transfer complete
       CWD /common2016-04
250 CWD command successful
       PASV
227 Entering Passive Mode (74,208,215,227,197,113).
       LIST -al
150 Opening ASCII mode data connection for file list
226 Transfer complete
       NOOP
200 NOOP command successful

Then, I select the 40,000 files in the directory and deletion begins
250 DELE command successful
       DELE 2016-0426-090747.jpg

Then, after about 10 minutes and 4,000 file deletions, the following occurs:

500 'FEAT': command unrecognized.
Unable to make a data connection. Please try again.
150 Opening ASCII mode data connection for file list
421 No transfer timeout (600 seconds): closing control connection
: /common2016-04/2016-0421-182455.jpg
421 Service not available, closing control connection.
: /common2016-04/2016-0421-182355.jpg
530 Not logged in.
: /common2016-04/2016-0421-182255.jpg
530 Not logged in.
: /common2016-04/2016-0421-182155.jpg

and it goes on and on, trying to delete file after file but giving the same 530 error.
Strange part is that immediately prior to this 600 second no transfer timeout, files are being successfully deleted.

Now, 600 seconds is 10 minutes and it seems that this is happening after 10 minutes.  Hmm...
It never used to happen until recently.

Help, please, anyone?
Thanks,
Jim

**Comment by mimecuvalo** [comment]
Hm, strange - not sure why it would quit halfway - you can try Filezilla and see if that helps?  It might be something with that particular server and deleting so many files at once.

**Comment by jimbabwe7** [comment]
Hi Mime, and thanks for getting back to me.  I've tried FileZilla and have basically the same problem.  I guess that points more likely than not to 1&1's servers, rather than the FTP program.

I shall try to get to the bottom of it with 1&1, though I do not have high confidence that I will be able to do so.
