### ISSUE TITLE
Cannot rename file

### ISSUE THREAD

**Issue by lidya1859** [mimecuvalo/fireftp#183]
I have updated to the latest version and I found out that I cannot rename my file. Neither in local nor server. When I try to rename file or folder, the filename went empty. And in server the filename didn't change. Can you help me please?
Thank you.

**Comment by mimecuvalo** [comment]
Hm, strange - is this on Windows, Mac, Linux?

**Comment by lidya1859** [comment]
I'm using Windows 10 with Firefox Developer Edition 52.0a2..

**Comment by S3ndG** [comment]
Hi,
a lot of people have this bug I guess : http://forums.mozillazine.org/viewforum.php?f=23&sid=9f1b653f53012fb4defdf27056da4f1d
I have also that bug with firefox 51b6, but NOT with firefox 50.0.2.
May you do something to fix this?
Thanks :-)

**Comment by ozstar** [comment]
Yes I have had it for a while too. 

I have 51.0b6 (64-bit) but it I had the same problem with the previous 2 or 3 builds.

I too cannot rename or create folders either in either panel.  I can delete and still import and export however.
I notice a small panel with FireFTP in it comes up when I have the wrong password in it. The usual Edit panel comes up but also a small 1" panel as well with a bar in it. Not sure whther it is meant or not.

I would like this fixed as I use it a lot.

**Comment by jg-github** [comment]
Hi from Berlin,

I, too, am having the renaming problem. I'm using the latest version of FireFTP on 64-bit Fx 51 and 53 on Win7Pro x64.

Thanks for fixing this.

**Comment by shivelier** [comment]
v2.0.28
Windows 10  x64

Do not create files and folders does not change the name!

**Comment by S3ndG** [comment]
Hi!
Are you gonna make changes to your extension for the release of firefox 51 at the end of the month?  ^_^

**Comment by newjie** [comment]
I had this annoying problem too! Hope you guys can get this fixed as soon as possible!

**Comment by mimecuvalo** [comment]
fixing going out to AMO today - will be in review for a couple days and then launched.
This was a regression with setCellText, filed bug for Mozilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1329907

Workaround here: https://github.com/mimecuvalo/fireftp/commit/f1061ee2d95af8d3954578a0c7ba0d9ebfaec5ef

thx!

**Comment by guanix12** [comment]
FIX FireFTP  Error PLEASE !!!! All Complaining about that

Drag and Drop files is no more possible.
"Error message=TypeError: event.dataTransfer.types.includes is not a function
URL=chrome://fireftp/content/js/etc/dragDrop.js
Line Number=29"

Please fix that FireFTP not work anymore.
