### ISSUE TITLE
update from version 2.0.5 to 2.0.29 gives drag and drop error

### ISSUE THREAD

**Issue by davepilbeam** [mimecuvalo/fireftp#185]
Firefox 50.1.0 on Windows 7 Professional

recent automatic update from version 2.0.5 to 2.0.29 has produced a drag and drop error - drag and drop no longer works in FireFTP panels:

error:
```
event.dataTransfer.types.includes is not a function
error line 29
```

current fix for me by rolling back to version 2.0.5...

**Comment by mimecuvalo** [comment]
Pushing out a fix - thanks for letting me know!
