### ISSUE TITLE
Fix FireFTP Error Please

### ISSUE THREAD

**Issue by guanix12** [mimecuvalo/fireftp#188]
Since 2 days ago i was trying to add files to FireFTP and i got this error :

Error message= TypeError: event.dataTransfer.types.includes is not a function
URL= chrome://fireftp/content/js/etc/dragDrop.js
Line Number= 29

Fix that please i cant do anything in FTP , lot of peoples complaining about that in FireFTP Reviews Page hope you find fix we realy need to use FTP :

https://addons.mozilla.org/en-US/firefox/addon/fireftp/reviews/

**Comment by mimecuvalo** [comment]
Fixed in the latest version - thanks for letting me know.
