### ISSUE TITLE
FireFTP 2.0.30 Error

### ISSUE THREAD

**Issue by guanix12** [mimecuvalo/fireftp#189]
Today i removed the 2.0.29 of FireFTP Version , and downloaded the newer one 2.0.30 and got that error :(

Error message= TypeError: 'contains' called on an object that does not implement interface DOMStringList.
URL= chrome://fireftp/content/js/etc/dragDrop.js
Line Number= 30

Hope you fix , 4 days we not able to use FTP

**Comment by mimecuvalo** [comment]
Thanks for the feedback, I'll fix it up.

**Comment by mimecuvalo** [comment]
Please upgrade to 2.0.31 and Firefox 51.
