### ISSUE TITLE
ERROR: connection via SFTP no longer works

### ISSUE THREAD

**Issue by Gramps** [mimecuvalo/fireftp#190]
A few days ago I started getting this error when connecting via SFTP:
```
Unable to make a connection. Please try again.
Error message= TypeError: self.client is null
URL= chrome://fireftp/content/js/connection/ssh2.js
Line Number= 52
```
It seems to have started randomly.  Not sure if it's a bad update or what.

**Comment by medicationforall** [comment]
I get the exact same error I'm running:
50.1.0 Mozilla Firefox for Linux Mint
FireFTP 2.0.30 - last updated on 01/20/2017

**Comment by Gramps** [comment]
Ah yes, I should mention I am on 50.1.0 Mozilla Firefox for Windows 10, using FireFTP 2.0.30.  I will test it on Ubuntu 16.04 soon.

**Comment by mimecuvalo** [comment]
I removed that version of FireFTP (2.0.30) because it had a bad build that led to SFTP problems.
Please upgrade to 2.0.31 and Firefox 51.

**Comment by Gramps** [comment]
Updated everything and we're back to normal!  Cheers, sir!
