### ISSUE TITLE
Strang Problem!

### ISSUE THREAD

**Issue by 85050** [mimecuvalo/fireftp#196]
Recently, whenever I try to load a specific website (News Website) I used to visit daily somehow got linked with my FireFTP which I use to access my personal web domain which has NOTHING to do with the above News Website.  My problem is that whenever I try to load this News Website it opens INSTEAD automatically FireFTP.  No matter what I do I cannot access this News Website.  If I remove FireFTP that News Website works fine as soon as I reinstall FireFTP then loading this News Website it opens INSTEAD automatically FireFTP.

Any help would be greatly appreciated.

**Comment by mimecuvalo** [comment]
Duplicate of #192
