### ISSUE TITLE
How to use it on Android.

### ISSUE THREAD

**Issue by ytrezq** [mimecuvalo/fireftp#209]
Sorry, but where is the fireftp start button in FireFox for Android?

**Comment by mimecuvalo** [comment]
It's not supported in Android unfortunately.

**Comment by ytrezq** [comment]
@mimecuvalo but if it wouldn’t be supported on Android,  I wouldn’t be able to install the extension in FireFox…

The ᴀᴘɪ is nearlly the same. There’s only one part to change in order to get it working on Android : the launch button…
