### ISSUE TITLE
How easy would porting FireFTP to Chrome-browser be?

### ISSUE THREAD

**Issue by SarasotaSlim** [mimecuvalo/fireftp#210]
FireFTP was the one app/addon that has kept me using Firefox.  (No problem...I just installed Waterfox.)

But, what I've been wishing for, is to find an equivalent that ran on Chrome (and hence Chrome-OS).

Just how different is a browser 'extension' for Chrome from  'addon'?  

[ If you were a betting man...what would you put the odds at, that someone will soon come along and port this to Chrome? Have you ever authored a Chrome extension? ]

**Comment by mimecuvalo** [comment]
I've tried porting to Chrome and have sat down in person with Chrome developers - it's not going to happen unfortunately :-/
