### ISSUE TITLE
Corrupt file

### ISSUE THREAD

**Issue by SadZumo** [mimecuvalo/fireftp#217]
When I try to install FTPFire add-on in Waterfox a notifications pulls up saying "Could not add because the file seems to be corrupt" and then disappears. Any tip?

**Comment by dapgo** [comment]
Which Waterfox? Classic or Current? 
I am sure that fireftp is not working on WF Current, but I am using it on Classic. 
If you need to use XUL addons you should stay on Classic

**Comment by SadZumo** [comment]
You're right, I just installed WF Classic and it works now. Thank you very much!
