### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by Pellesius** [mimecuvalo/fireftp#219]
Hello,
installing FireFTP does not work for me:

![FireFTP](https://user-images.githubusercontent.com/62651601/101803049-654d1c80-3b10-11eb-95f4-bad700c1edc4.png)

**Comment by SvnGms** [comment]
They state this in the Readme:

![image](https://user-images.githubusercontent.com/61502377/101813701-591b8c00-3b1d-11eb-8463-98894509007a.png)

**Comment by dapgo** [comment]
And specifically it has to be Waterfox Classic  because the other 2 versions of Waterfox will not run Fireftp. BTW also Basilisk or Palemoon will allow you to use Fireftp
