### ISSUE TITLE
Fireftp and blue griffon

### ISSUE THREAD

**Issue by FaltschWagoni** [mimecuvalo/fireftp#220]

**Comment by FaltschWagoni** [comment]
I want to use fireftp in blue griffon for loading up and down files to my website. fireftp gets connected to the ftp-server, but doesn't built a list of the included website-files. it's still working and working, but nothing's happening.

**Comment by FaltschWagoni** [comment]
in addition: I'm using fireftp on a apple notbook Mac OS 11.0.1

**Comment by FaltschWagoni** [comment]
in addition: log entry when trying to connect server

200 Using ASCII mode to transfer data.
        PASV
227 Entering Passive Mode (0,0,0,1,141,131)
       LIST
150 Opening ASCII mode data connection.
220 Speak friend, and enter
       USER (Url)
331 login okay, send password.
       PASS (password not shown)
230 User logged in, proceed.
        CWD /
250 Directory changed to /
        TYPE A

so far, and then ist starts again from 200 ... and so on

**Comment by mimecuvalo** [comment]
Sorry, I've ended support / development of the addons as noted on fireftp.net
