### ISSUE TITLE
Private Key login isn't working

### ISSUE THREAD

**Issue by wolfgangrumpf** [mimecuvalo/fireftp#221]
My web server requires ssh keys to access.  This works fine with ssh.  I have configured FireFTP to use the same key, port 22, sftp, and it ALWAYS:

1.  Brings up a username/password dialog
2. Tells me that authentication failed

I'm using version 2.0.31 with ssh components 1.7.7.1

**Comment by mimecuvalo** [comment]
Hello! While I'd love to continue providing support FireFTP it's reached end-of-life and not supported anymore unfortunately.
